Revisao Cards 1 a 4
danilohumbertozup/pagamento pull request #1
Opened 2020-05-18 23:25 UTC by danilohumbertozup

2020-05-19 10:55 UTC, albertotavareszup requested changes
Opa Danilo, aqui no PR não tem o código relativo ao cartão "Criação do ambiente necessário para listar pagamentos de um determinado usuário para um determinado restaurante" . Lembrando que não precisa fazer um fluxo padrão isso... pode ser um endpoint que quando acessado grave todas as coisas, uma inicialização ali no projeto que popule um banco em memória etc.

2020-05-22 20:33 UTC, albertotavareszup requested changes
Acho que só precisa ajeitar as formas de pagamento no usuário.

2020-05-22 20:33 UTC, albertotavareszup commented on src/main/kotlin/com/zup/pagamento/model/FormaPagamento.kt
> +    var id: Long = 0
Ahhh, o pior que aqui o valor do id realmente é nulo, é uma realidade.

2020-05-22 20:33 UTC, albertotavareszup commented on src/main/kotlin/com/zup/pagamento/model/TipoPagamento.kt
> +        var pagamentoOnline: Boolean) {
Aqui você pode usar o tipo primitivo, que aí você já garante na compilação não aceitar nulo. Se o kotlin não suportar, ok.

2020-05-22 20:33 UTC, albertotavareszup commented on src/main/kotlin/com/zup/pagamento/model/Usuario.kt
> +        var formaPagamento: FormaPagamento) {
O usuário pode aceitar um conjunto de formas de pagamento.

2020-05-22 23:36 UTC, danilohumbertozup commented on src/main/kotlin/com/zup/pagamento/model/Usuario.kt
> +        var formaPagamento: FormaPagamento) {
Corrigido

2020-05-22 23:36 UTC, danilohumbertozup commented on src/main/kotlin/com/zup/pagamento/model/FormaPagamento.kt
> +    var id: Long = 0
Corrigido

2020-05-22 23:37 UTC, danilohumbertozup commented on src/main/kotlin/com/zup/pagamento/model/TipoPagamento.kt
> +        var pagamentoOnline: Boolean) {
Não suportado.

2020-05-24 09:40 UTC, albertotavareszup approved these changes
Boa! Não lembro agora, mas é importante que a Forma de Pagamento tenha um equals e hashcode. Nesse caso, pode considerar a descrição da forma como o atributo de comparação. Não podemos ter duas formas com a mesma descrição.

2020-05-26 12:55 UTC, merged